# Generated by Django 5.1.6 on 2025-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('borrower_perms', 'Global borrower permissions'), ('lender_perms', 'Global lender permissions')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
