# Generated by Django 4.2.19 on 2025-02-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_addressfield_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
