# Generated by Django 5.1.6 on 2025-03-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_fname_profile_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='products\\static\\products\\images\\placeholder-image.jpg', upload_to='media/'),
        ),
    ]
