# Generated by Django 5.1.6 on 2025-03-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
