# Generated by Django 4.2.19 on 2025-03-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0004_delete_addressfield_profile_address_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_perms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
