# Generated by Django 4.2.19 on 2025-03-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_profile_group_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group_perms',
        ),
    ]
