# Generated by Django 5.1.7 on 2025-03-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_alter_profile_image"),
        ("login", "0006_remove_profile_group_perms"),
    ]

    operations = []
