# Generated by Django 5.1.7 on 2025-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productCollections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="collection_creator",
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_privacy",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
    ]
