# Generated by Django 5.1.7 on 2025-03-22 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productCollections", "0002_remove_collection_collection_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="collection_private_userlist",
        ),
        migrations.AddField(
            model_name="collection",
            name="collection_private_userlist",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
