# Generated by Django 5.1.1 on 2025-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCollections', '0005_alter_collection_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='equipments', to='productCollections.collection')),
            ],
        ),
    ]
