# Generated by Django 5.1.7 on 2025-03-29 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productCollections", "0006_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="collection_private_userlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="productCollections_private_userlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productCollections_owned_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
