# Generated by Django 5.1.7 on 2025-03-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "productCollections",
            "0007_alter_collection_collection_private_userlist_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="collections",
        ),
    ]
