# Generated by Django 5.1.6 on 2025-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productCollections', '0008_remove_equipment_collections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
