# Generated by Django 5.1.6 on 2025-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('ball', 'Ball Sports'), ('racket', 'Racket Sports'), ('fitness', 'Fitness Equipment'), ('indoor', 'indoor Sports'), ('water', 'Water Sports'), ('winter', 'Winter Sports'), ('extreme', 'extreme Sports')], max_length=20),
        ),
    ]
