# Generated by Django 5.1.6 on 2025-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.FileField(default='products\\static\\products\\images\\placeholder-image.jpg', upload_to='media/'),
        ),
    ]
