# Generated by Django 5.1.6 on 2025-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
