# Generated by Django 5.1.6 on 2025-03-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
        ('products', '0006_alter_equipment_image'),
    ]

    operations = [
    ]
