# Generated by Django 5.1.7 on 2025-03-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productCollections", "0008_remove_equipment_collections"),
        ("products", "0007_merge_0003_review_0006_alter_equipment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="equipment", to="productCollections.collection"
            ),
        ),
    ]
