# Generated by Django 5.1.6 on 2025-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_0003_review_0006_alter_equipment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_available',
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'unavailable')], default='available', max_length=20),
        ),
    ]
