# Generated by Django 5.1.7 on 2025-03-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_equipment_collections"),
        ("products", "0009_rental"),
    ]

    operations = []
