# Generated by Django 5.1.7 on 2025-03-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_merge_0008_equipment_collections_0009_rental"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
