# Generated by Django 5.1.6 on 2025-04-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_equipment_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.TextField(default='example_location'),
            preserve_default=False,
        ),
    ]
