# Generated by Django 5.1.6 on 2025-04-11 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_borrow_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
