# Generated by Django 5.1.6 on 2025-04-11 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_borrow_request_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddConstraint(
            model_name='borrow_request',
            constraint=models.UniqueConstraint(fields=('equipment', 'user'), name='request_only_once'),
        ),
    ]
