# Generated by Django 5.1.5 on 2025-04-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_rental_rental_date'),
        ('products', '0016_alter_borrow_request_user'),
    ]

    operations = [
    ]
